version: "3"

silent: true

vars:
  RUFF_ENABLE: "{{ .RUFF_ENABLE | default true }}"
  MYPY_ENABLE: "{{ .MYPY_ENABLE | default true }}"
  VULTURE_ENABLE: "{{ .VULTURE_ENABLE | default true }}"

  ENVIRONMENT: '{{ .ENVIRONMENT | default "release" }}'

tasks:
  default:
    deps:
      - info

  info:
    desc: Prints application info
    cmds:
      - echo "---"
      - poetry version
      - echo "---"

  lint:
    desc: Linters for application cleanup
    cmds:
      - task: lint-ruff
      - task: lint-mypy
      - task: lint-vulture
  lint-ruff:
    desc: Linters for application cleanup
    cmds:
      - echo "-- lint-ruff (enabled={{ .RUFF_ENABLE }}) --"
      - '{{ if eq .RUFF_ENABLE "true" }} ruff check {{ .CLI_ARGS }} . {{ end }}'
  lint-mypy:
    desc: Linters for application cleanup
    cmds:
      - echo "-- lint-mypy (enabled={{ .MYPY_ENABLE }}) --"
      - '{{ if eq .MYPY_ENABLE "true" }} poetry install --only linter --no-root {{ end }}'
      - '{{ if eq .MYPY_ENABLE "true" }} mypy --show-error-codes . {{ end }}'
  lint-vulture:
    desc: Linters for application cleanup
    cmds:
      - echo "-- lint-vulture (enabled={{ .VULTURE_ENABLE }}) --"
      - '{{ if eq .VULTURE_ENABLE "true" }} vulture . .vulture-whitelist.cfg {{ end }}'

  # Deps
  deps:
    desc: Обновление зависимостей
    cmd: poetry lock {{ if eq .FROZEN "false" }} --regenerate {{ end }}
  deps-install:
    cmds:
      - poetry install --no-root --only {{ .GROUPS }}
    vars:
      GROUPS:
        sh: case "{{ .ENVIRONMENT }}" in
          "develop" ) echo "main,tests,linter,dev" ;;
          "linting" ) echo "main,linter" ;;
          "testing" ) echo "main,tests" ;;
          * ) echo "main" ;;
          esac

  build:
    desc: Project build
    cmds:
      - poetry build -n

  publish:
    desc: Publish package to PyPI
    cmds:
      - poetry publish
