name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install task
        uses: pnorton5432/setup-task@v1.0.0
        with:
          task-version: 3.29.1
      - name: Install poetry
        uses: snk-devops/action.poetry.install@master
        with:
          os: ubuntu
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          task deps deps-install ENVIRONMENT=linting -v
      - name: Lint
        run: task lint
